### PR TITLE
feat: added product page

### PR DESCRIPTION
**Pull request by sharmivijay**
Kindly review and add your comments

### CODE REVIEW

**Comment by sharmivijay** [comment]
yet to deploy the app

**Comment by sharmivijay** [comment]
Preview added from local machine for your reference
image

**Review by raghav2110 — APPROVED** [review]
Card images can be of same size. CSS naming are upto the point. Code looks clean.

**Review by MonikaJhingan — APPROVED** [review]
The code is well indented and looks good to be merged just take care of the extra blank spaces.

**Pull request merged**
