### PR TITLE
feat: added home age

### PR DESCRIPTION
**Pull request by sharmivijay**
Kindly review and your comments

### CODE REVIEW

**Comment by sharmivijay** [comment]
yet to deploy the app

**Comment by sharmivijay** [comment]
deployed the app

**Comment by sharmivijay** [comment]
Preview for your reference
image

**Review by MonikaJhingan — APPROVED** [review]
The code looks good to be merged just remove the extra spaces for later projects.

**Review by dev-enforced — APPROVED** [review]
The code and demonstration looks good to me!! For social media you can add target=_blank so that it opens in a new tab later on

**Pull request merged**
